### ISSUE TITLE
API Crashes

### ISSUE THREAD

**Issue by RjMakwana2660** [Persie0/SimplyTranslate-dart#1]
API Keeps crashes when you send request with 3 times different words

**Comment by Persie0** [comment]
Could you send your code so I can reproduce the error?
Switched to post method in version 1.0.8 (yesterday) as I also had problems with the package when implemented in an actual app (when translating longer texts) - does the problem still persist?
The example code that also makes multiple requests worked fine yesterday (and also in previous versions).

Update: Just updated the package again (1.1.0)- it changes the instance now after each request and this error should not occur anymore (only if you spam requests) an alternative solution would be to wait some time between requests.

**Comment by Persie0** [comment]
in v1.1.1 all errors should be fixed - see changelog
