### ISSUE TITLE
Connection fails

### ISSUE THREAD

**Issue by AirtonGamer** [Persie0/SimplyTranslate-dart#2]
When i try to use the package the connection fails and keep giving errors

code: 

`import 'package:flutter/foundation.dart';
import "package:simplytranslate/simplytranslate.dart";

class Providertest with ChangeNotifier {
  //Translate From specific language
  String transLang = "English";
  String transCode = "en";

  //Translate To specific language
  String transInLang = "Arabic";
  String transInCode = "ar";

  String switcher = "";
  String switcherCode = "";

  String inputData = "";

  SimplyTranslator gt = SimplyTranslator(EngineType.google);
  //gt.setInstance = "simplytranslate.pussthecat.org";

  String textResult = "";

void translateFunc() async {
    textResult = await gt.trSimply(inputData, transCode, transInCode);
    notifyListeners();
  }
}`

error messages:

this: `ClientException (Error 500:

 <!doctype html>
<html lang=en>
<title>500 Internal Server Error</title>
<h1>Internal Server Error</h1>
<p>The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.</p>
)`

and this is the log in console:

`
[ERROR:flutter/lib/ui/ui_dart_state.cc(198)] Unhandled Exception: Connection failed
#0      IOClient.send
package:http/src/io_client.dart:88
<asynchronous suspension>
#1      BaseClient._sendUnstreamed
package:http/src/base_client.dart:93
<asynchronous suspension>
#2      _withClient
package:http/http.dart:164
<asynchronous suspension>
#3      SimplyTranslator.trSimply
package:simplytranslate/src/translator.dart:193
<asynchronous suspension>
#4      Providertest.translateFunc
package:ksynonyms/provider.dart:57
<asynchronous suspension>
`

**Comment by Persie0** [comment]
A instance  is probably no longer working.
As I can't always update the package when they add/remove an instance -
You could try 
`gt.updateSimplyInstances();` to update them or use `gt.translateSimply(
      " difficult.",
      from: 'en',
      to: 'de',
      instanceMode: InstanceMode.Loop,
      retries: 4)` (look at the example, how to use it) which automatically retries (4 times) with another instance if 
 it's is not working

**Comment by AirtonGamer** [comment]
Well i tried but also failed see this code:

`import 'package:flutter/foundation.dart';
import "package:simplytranslate/simplytranslate.dart";

class Providertest with ChangeNotifier {
  //Translate From specific language
  String transLang = "English";
  String transCode = "en";

  //Translate To specific language
  String transInLang = "Arabic";
  String transInCode = "ar";

  String switcher = "";
  String switcherCode = "";

  String inputData = "";

  SimplyTranslator gt = SimplyTranslator(EngineType.google);

  String textResult = "";




  void saveInput(String value) {
    inputData = value;
    gt.setInstance = "simplytranslate.org";
    gt.updateSimplyInstances();
    notifyListeners();
  }

  void translateFunc() async {
    gt.updateSimplyInstances();
    textResult = await gt.trSimply(inputData, transCode, transInCode);
    gt.updateSimplyInstances();
    notifyListeners();
  }
}
`


but also dont work this is the error:

Exception has occurred.
HandshakeException (HandshakeException: Handshake error in client (OS Error: 
	CERTIFICATE_VERIFY_FAILED: certificate has expired(handshake.cc:393)))

this is debug log:

`Restarted application in 5,576ms.
[ERROR:flutter/lib/ui/ui_dart_state.cc(198)] Unhandled Exception: HandshakeException: Handshake error in client (OS Error:
	CERTIFICATE_VERIFY_FAILED: certificate has expired(handshake.cc:393))
#0      _SecureFilterImpl._handshake (dart:io-patch/secure_socket_patch.dart:99:46)
#1      _SecureFilterImpl.handshake (dart:io-patch/secure_socket_patch.dart:142:25)
#2      _RawSecureSocket._secureHandshake (dart:io/secure_socket.dart:911:54)
#3      _RawSecureSocket._tryFilter (dart:io/secure_socket.dart:1040:19)
<asynchronous suspension>
[ERROR:flutter/lib/ui/ui_dart_state.cc(198)] Unhandled Exception: HandshakeException: Handshake error in client (OS Error:
	CERTIFICATE_VERIFY_FAILED: certificate has expired(handshake.cc:393))
#0      _SecureFilterImpl._handshake (dart:io-patch/secure_socket_patch.dart:99:46)
#1      _SecureFilterImpl.handshake (dart:io-patch/secure_socket_patch.dart:142:25)
#2      _RawSecureSocket._secureHandshake (dart:io/secure_socket.dart:911:54)
#3      _RawSecureSocket._closeHandler (dart:io/secure_socket.dart:904:15)
#4      _RawSecureSocket._eventDispatcher (dart:io/secure_socket.dart:847:9)
#5      _rootRunUnary (dart:async/zone.dart:1442:13)
#6      _CustomZone.runUnary (dart:async/zone.dart:1335:19)
#7      _CustomZone.runUnaryGuarded (dart:async/zone.dart:1244:7)
#8      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341:11)
#9      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
#10     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:774:19)
#11     _StreamController._add (dart:async/stream_controller.dart:648:7)
#12     _StreamController.add (dart:async/stream_controller.dart:596:5)
#13     new _RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1846:35)
#14     _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:1315:18)
#15     _microtaskLoop (dart:async/schedule_microtask.dart:40:21)
#16     _startMicrotaskLoop (dart:async/schedule_microtask.dart:49:5)
`

**Comment by Persie0** [comment]
https://stackoverflow.com/questions/54285172/how-to-solve-flutter-certificate-verify-failed-error-while-performing-a-post-req
Should solve it

Reopen this issue if not
