### ISSUE TITLE
How should I get the UK accent of TTS?

### ISSUE THREAD

**Issue by Mae623** [Persie0/SimplyTranslate-dart#3]
the lang parameter only support 'en' .

**Comment by Mae623** [comment]
can I config more TTS options?

**Comment by Persie0** [comment]
Simplytranslate does not support accents. I am not assoziated with them but you could open an issue at: https://codeberg.org/SimpleWeb/SimplyTranslate-Web/issues

**Comment by joyjiyuan** [comment]
> Simplytranslate does not support accents. I am not assoziated with them but you could open an issue at: https://codeberg.org/SimpleWeb/SimplyTranslate-Web/issues

OK, i have submit it on codeberg. Thank you.
